// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nmgwcavicouhekywqkpt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5tZ3djYXZpY291aGVreXdxa3B0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzNTQ2MTcsImV4cCI6MjA2NjkzMDYxN30.btooWm8oxDAK_x_t4fxoa013pfL-XtiWaMVuye7TMgw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});